spring.application.name=Product Service

# Actuator Info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Product Service
info.app.version=1.1.1
info.app.description= A backend system for the E-commerce

spring.profiles.active = dev

# Jwt Application
spring.jwt.secret=${JWT_SECRET}
spring.jwt.accessTokenExpiration=3600
spring.jwt.refreshTokenExpiration=1209600

stripe.secretKey =
stripe.webhookSecretKey =

# OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# Redis
spring.redis.host=localhost
spring.redis.port=6379
# Eureka
server.port= 8000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/